# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "review-embed"
client_id = "ff60c711b66756890cff1b0a073b6e30"
application_url = "https://fa-expression-airplane-amazing.trycloudflare.com"
embedded = true
handle = "bryt-design-challenge"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
write_products = "write_products"

[auth]
redirect_urls = [
  "https://fa-expression-airplane-amazing.trycloudflare.com/auth/callback",
  "https://fa-expression-airplane-amazing.trycloudflare.com/auth/shopify/callback",
  "https://fa-expression-airplane-amazing.trycloudflare.com/api/auth/callback"
]
embedded_app_url = "https://fa-expression-airplane-amazing.trycloudflare.com"

[pos]
embedded = false

[app_proxy]
url = "https://fa-expression-airplane-amazing.trycloudflare.com"
subpath = "api"
prefix = "apps"
